# Generated by Django 5.1.4 on 2025-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawOrderParser', '0002_category_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_tag',
            field=models.CharField(db_index=True, default=None, max_length=100, verbose_name='Тег категории'),
        ),
    ]
