# Generated by Django 5.1.4 on 2025-01-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawOrderParser', '0003_alter_category_category_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Инстанция')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Инстанция',
                'verbose_name_plural': 'Инстанции',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='documents',
            name='document_instance',
        ),
        migrations.AddField(
            model_name='documents',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LawOrderParser.instance', verbose_name='Инстанция документа'),
        ),
    ]
