# Generated by Django 5.1.4 on 2025-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawOrderParser', '0004_instance_remove_documents_document_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_tag',
            field=models.CharField(db_index=True, default='***', max_length=100, verbose_name='Тег инстанции'),
        ),
    ]
